version: "3"
services:
  coursematerial:
    image: sahilrajput03/docker-hy.github.io
    ports:
      - 4000:80
    container_name: coursematerial
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      # default ^^ for this is `86400` i.e., 24 hrs, so chaing it `300` i.e., 5 mins.
      - TZ=Asia/Calcutta
