version: "3.2"
services:
  calculator:
    build: ./calculator
    image: calculator
    ports:
      - 3000:3000
    container_name: calculator

  compute:
    build: ./compute
    image: compute
    environment:
      #     - VIRTUAL_HOST=compute.localtest.me
      # Now, below wildcard thing works for all domains, for e.g.,
      # compute.localtest.me, compute.lvh.me, compute.localtest.me, compute.vcap.me.
      - VIRTUAL_HOST=compute.*

  load-balancer:
    build: ./load-balancer
    image: load-balancer
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    container_name: load-balancer
